### ISSUE TITLE
ImportError: No module named nfft

### ISSUE THREAD

**Issue by nschloe** [pyNFFT/pyNFFT#11]
After a clean

```
$ pip install pynfft
```

I'm getting

```
>> import pynfft
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-ffdd6b9d3711> in <module>()
----> 1 import pynfft

/home/nschloe/software/pyNFFT/pyNFFT-1.2/pynfft/__init__.py in <module>()
     17 # along with this program. If not, see <http://www.gnu.org/licenses/>.
     18 
---> 19 from .nfft import NFFT, Solver
     20 import util

ImportError: No module named nfft
```

**Comment by DrSAR** [comment]
On Version 1.3.2 and with 3358e29 obviously using absolute importing:
``` python
from pynfft.version import version as __version__
from pynfft.nfft import NFFT
from pynfft.solver import Solver
```
I am still getting this error on python 2.7:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pynfft/__init__.py", line 20, in <module>
    from pynfft.nfft import NFFT
ImportError: No module named nfft
```

**Comment by DrSAR** [comment]
I tried this on ubuntu with package-system provided fftw3 and nfft as well as on mac. The error I get is the same and seems to indicate that I'm doing the same thing wrong. Any help?

**Comment by DrSAR** [comment]
Pls excuse the noise and leave issue closed: I was trying to test (and import) while still in the build directories and it must have picked up the wrong module. In normal operation there is no problem.
