### ISSUE TITLE
setup: support for Windows installation

### ISSUE THREAD

**Issue by bs448c** [pyNFFT/pyNFFT#16]
Hi,

I'm having trouble setting up pyNFFT using Windows 8.1 and an Anaconda (v 1.9.1) Python install (64 bit machine).

I made sure I fulfill all requirements --

python 2.7.6
numpy 1.8
cython 0.20.1
nfft 3.2.3

Using Anaconda or Cygwin, when I try to `pip install pynfft` I get:

(any help would be appreciated)

```
C:\Users\Benjamin\Anaconda\Scripts\pip-script.py run on 05/07/14 22:06:41
Downloading/unpacking pynfft
  Getting page https://pypi.python.org/simple/pynfft/
  URLs to search for versions for pynfft:
  * https://pypi.python.org/simple/pynfft/
  Analyzing links from page https://pypi.python.org/simple/pyNFFT/
    Found link https://pypi.python.org/packages/source/p/pyNFFT/pyNFFT-1.1.0.tar.gz#md5=0cd6bbf10b65925cbe792df78701cb6d (from https://pypi.python.org/simple/pyNFFT/), version: 1.1.0
    Found link https://pypi.python.org/packages/source/p/pyNFFT/pyNFFT-1.1.1.tar.gz#md5=5aacb5b95b8df7ccd40191215998d698 (from https://pypi.python.org/simple/pyNFFT/), version: 1.1.1
    Found link https://pypi.python.org/packages/source/p/pyNFFT/pyNFFT-1.2.1.tar.gz#md5=f18f560780302dbdbf4fd9159d9ce653 (from https://pypi.python.org/simple/pyNFFT/), version: 1.2.1
    Found link https://pypi.python.org/packages/source/p/pyNFFT/pyNFFT-1.2.2.tar.gz#md5=f61efae19c8f3b34b5f4fdf814905874 (from https://pypi.python.org/simple/pyNFFT/), version: 1.2.2
    Found link https://pypi.python.org/packages/source/p/pyNFFT/pyNFFT-1.2.3.tar.gz#md5=34a4c396ed3b4af4040acb1560c93308 (from https://pypi.python.org/simple/pyNFFT/), version: 1.2.3
    Found link https://pypi.python.org/packages/source/p/pyNFFT/pyNFFT-1.2.tar.gz#md5=c88818acf60ffed191b30aeed9f129ac (from https://pypi.python.org/simple/pyNFFT/), version: 1.2
    Found link https://pypi.python.org/packages/source/p/pyNFFT/pyNFFT-1.3.0-dev.tar.gz#md5=d84022765bf7fea79732d070f4c209f2 (from https://pypi.python.org/simple/pyNFFT/), version: 1.3.0-dev
  Ignoring link https://pypi.python.org/packages/source/p/pyNFFT/pyNFFT-1.3.0-dev.tar.gz#md5=d84022765bf7fea79732d070f4c209f2 (from https://pypi.python.org/simple/pyNFFT/), version 1.3.0-dev is a pre-release (use --pre to allow).
  Using version 1.2.3 (newest of versions: 1.2.3, 1.2.2, 1.2.1, 1.2, 1.1.1, 1.1.0)
  Downloading pyNFFT-1.2.3.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/p/pyNFFT/pyNFFT-1.2.3.tar.gz#md5=34a4c396ed3b4af4040acb1560c93308 (from https://pypi.python.org/simple/pyNFFT/)
  Running setup.py (path:c:\users\benjamin\appdata\local\temp\pip_build_Benjamin\pynfft\setup.py) egg_info for package pynfft
    running egg_info
    creating pip-egg-info\pyNFFT.egg-info
    writing requirements to pip-egg-info\pyNFFT.egg-info\requires.txt
    writing pip-egg-info\pyNFFT.egg-info\PKG-INFO
    writing top-level names to pip-egg-info\pyNFFT.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\pyNFFT.egg-info\dependency_links.txt
    writing manifest file 'pip-egg-info\pyNFFT.egg-info\SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info\pyNFFT.egg-info\SOURCES.txt'
    writing manifest file 'pip-egg-info\pyNFFT.egg-info\SOURCES.txt'
  Source in c:\users\benjamin\appdata\local\temp\pip_build_benjamin\pynfft has version 1.2.3, which satisfies requirement pynfft
Requirement already satisfied (use --upgrade to upgrade): numpy in c:\users\benjamin\anaconda\lib\site-packages (from pynfft)
Requirement already satisfied (use --upgrade to upgrade): cython in c:\users\benjamin\anaconda\lib\site-packages (from pynfft)
Installing collected packages: pynfft
  Running setup.py install for pynfft
    Running command C:\Users\Benjamin\Anaconda\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\benjamin\\appdata\\local\\temp\\pip_build_Benjamin\\pynfft\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\benjamin\appdata\local\temp\pip-mvpyjj-record\install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\pynfft
    copying pynfft\__init__.py -> build\lib.win-amd64-2.7\pynfft
    running build_ext
    cythoning c:\users\benjamin\appdata\local\temp\pip_build_Benjamin\pynfft\pynfft\nfft.pyx to c:\users\benjamin\appdata\local\temp\pip_build_Benjamin\pynfft\pynfft\nfft.c
    building 'pynfft.nfft' extension
    C:\Users\Benjamin\Anaconda\Scripts\gcc.bat -DMS_WIN64 -mdll -O -Wall -IC:\Users\Benjamin\Anaconda\lib\site-packages\numpy\core\include -IC:\Users\Benjamin\Anaconda\include -IC:\Users\Benjamin\Anaconda\PC -IC:\Users\Benjamin\Anaconda\lib\site-packages\numpy\core\include -IC:\Users\Benjamin\Anaconda\include -IC:\Users\Benjamin\Anaconda\PC -c c:\users\benjamin\appdata\local\temp\pip_build_Benjamin\pynfft\pynfft\nfft.c -o c:\users\benjamin\appdata\local\temp\pip_build_benjamin\pynfft\pynfft\nfft.o -O3 -fomit-frame-pointer -malign-double -fstrict-aliasing -ffast-math
    In file included from C:\Users\Benjamin\Anaconda\lib\site-packages\numpy\core\include/numpy/ndarraytypes.h:1760:0,
                     from C:\Users\Benjamin\Anaconda\lib\site-packages\numpy\core\include/numpy/ndarrayobject.h:17,
                     from C:\Users\Benjamin\Anaconda\lib\site-packages\numpy\core\include/numpy/arrayobject.h:4,
                     from c:\users\benjamin\appdata\local\temp\pip_build_Benjamin\pynfft\pynfft\nfft.c:346:
    C:\Users\Benjamin\Anaconda\lib\site-packages\numpy\core\include/numpy/npy_1_7_deprecated_api.h:12:9: note: #pragma message: C:\Users\Benjamin\Anaconda\lib\site-packages\numpy\core\include/numpy/npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
    c:\users\benjamin\appdata\local\temp\pip_build_Benjamin\pynfft\pynfft\nfft.c:349:19: fatal error: nfft3.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    Complete output from command C:\Users\Benjamin\Anaconda\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\benjamin\\appdata\\local\\temp\\pip_build_Benjamin\\pynfft\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\benjamin\appdata\local\temp\pip-mvpyjj-record\install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build\lib.win-amd64-2.7

creating build\lib.win-amd64-2.7\pynfft

copying pynfft\__init__.py -> build\lib.win-amd64-2.7\pynfft

running build_ext

cythoning c:\users\benjamin\appdata\local\temp\pip_build_Benjamin\pynfft\pynfft\nfft.pyx to c:\users\benjamin\appdata\local\temp\pip_build_Benjamin\pynfft\pynfft\nfft.c

building 'pynfft.nfft' extension

C:\Users\Benjamin\Anaconda\Scripts\gcc.bat -DMS_WIN64 -mdll -O -Wall -IC:\Users\Benjamin\Anaconda\lib\site-packages\numpy\core\include -IC:\Users\Benjamin\Anaconda\include -IC:\Users\Benjamin\Anaconda\PC -IC:\Users\Benjamin\Anaconda\lib\site-packages\numpy\core\include -IC:\Users\Benjamin\Anaconda\include -IC:\Users\Benjamin\Anaconda\PC -c c:\users\benjamin\appdata\local\temp\pip_build_Benjamin\pynfft\pynfft\nfft.c -o c:\users\benjamin\appdata\local\temp\pip_build_benjamin\pynfft\pynfft\nfft.o -O3 -fomit-frame-pointer -malign-double -fstrict-aliasing -ffast-math

In file included from C:\Users\Benjamin\Anaconda\lib\site-packages\numpy\core\include/numpy/ndarraytypes.h:1760:0,

                 from C:\Users\Benjamin\Anaconda\lib\site-packages\numpy\core\include/numpy/ndarrayobject.h:17,

                 from C:\Users\Benjamin\Anaconda\lib\site-packages\numpy\core\include/numpy/arrayobject.h:4,

                 from c:\users\benjamin\appdata\local\temp\pip_build_Benjamin\pynfft\pynfft\nfft.c:346:

C:\Users\Benjamin\Anaconda\lib\site-packages\numpy\core\include/numpy/npy_1_7_deprecated_api.h:12:9: note: #pragma message: C:\Users\Benjamin\Anaconda\lib\site-packages\numpy\core\include/numpy/npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION

c:\users\benjamin\appdata\local\temp\pip_build_Benjamin\pynfft\pynfft\nfft.c:349:19: fatal error: nfft3.h: No such file or directory

compilation terminated.

error: command 'gcc' failed with exit status 1

----------------------------------------
Cleaning up...
  Removing temporary dir c:\users\benjamin\appdata\local\temp\pip_build_Benjamin...
Command C:\Users\Benjamin\Anaconda\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\benjamin\\appdata\\local\\temp\\pip_build_Benjamin\\pynfft\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\benjamin\appdata\local\temp\pip-mvpyjj-record\install-record.txt --single-version-externally-managed --compile failed with error code 1 in c:\users\benjamin\appdata\local\temp\pip_build_Benjamin\pynfft
Exception information:
Traceback (most recent call last):
  File "C:\Users\Benjamin\Anaconda\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\Users\Benjamin\Anaconda\lib\site-packages\pip\commands\install.py", line 279, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "C:\Users\Benjamin\Anaconda\lib\site-packages\pip\req.py", line 1380, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "C:\Users\Benjamin\Anaconda\lib\site-packages\pip\req.py", line 699, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "C:\Users\Benjamin\Anaconda\lib\site-packages\pip\util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command C:\Users\Benjamin\Anaconda\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\benjamin\\appdata\\local\\temp\\pip_build_Benjamin\\pynfft\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\benjamin\appdata\local\temp\pip-mvpyjj-record\install-record.txt --single-version-externally-managed --compile failed with error code 1 in c:\users\benjamin\appdata\local\temp\pip_build_Benjamin\pynfft
```

**Comment by michaelmarty** [comment]
Hi all,
Tried to follow the tutorial at 4chem, but I keep getting a problem with the libnfft3_threads.dll not being recognized when I execute python setup.py ... Any suggestions? All other compilation works fine. Also, is there a way you could email or post the windows binaries (like http://www.lfd.uci.edu/~gohlke/pythonlibs/ or even just a zip of the pynfft folder)? It would be hugely helpful.
Thanks!
