### ISSUE TITLE
BUG: PyNFFT installation fails with Cython 3.0.0

### ISSUE THREAD

**Issue by paquiteau** [pyNFFT/pyNFFT#75]
Hello there, 
While doing the integration of PyNFFT in mind-inria/mri-nufft, a recent installation revealed that a `pip install pynfft` or `pip install pynfft2` results in a failed installation. This is due to the 3.0.0 version from Cython [^1] installing with Cython 0.29 works.

Here are the errors:
```
$ python setup.py install
/home/pc266769/gits/nsp/code/pyNFFT/setup.py:99: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.core import Command
Compiling /home/pc266769/gits/nsp/code/pyNFFT/pynfft/nfft.pyx because it changed.
Compiling /home/pc266769/gits/nsp/code/pyNFFT/pynfft/solver.pyx because it changed.
Compiling /home/pc266769/gits/nsp/code/pyNFFT/pynfft/util.pyx because it changed.
[1/3] Cythonizing /home/pc266769/gits/nsp/code/pyNFFT/pynfft/nfft.pyx
/volatile/pierre-antoine/.pyenv/versions/fmri/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/pc266769/gits/nsp/code/pyNFFT/pynfft/nfft.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

from cnfft3 cimport nfft_plan
^
------------------------------------------------------------

pynfft/nfft.pxd:18:0: 'cnfft3.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

from cnfft3 cimport nfft_plan
^
------------------------------------------------------------

pynfft/nfft.pxd:18:0: 'cnfft3/nfft_plan.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
cdef object nfft_flags_dict
cdef object fftw_flags_dict
cdef object nfft_supported_flags_tuple

cdef class NFFT(object):
    cdef nfft_plan _plan
         ^
------------------------------------------------------------

pynfft/nfft.pxd:25:9: 'nfft_plan' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
# Numpy must be initialized. When using numpy from C or Cython you must
# _always_ do that, or you will have segfaults
np.import_array()

# initialize FFTW threads
fftw_init_threads()
^
------------------------------------------------------------

pynfft/nfft.pyx:34:0: undeclared name not builtin: fftw_init_threads

Error compiling Cython file:
------------------------------------------------------------
...
# register cleanup callbacks
cdef void _cleanup():
    fftw_cleanup()
    fftw_cleanup_threads()

Py_AtExit(_cleanup)
          ^
------------------------------------------------------------

pynfft/nfft.pyx:41:10: Cannot assign type 'void (void) except *' to 'void (*)(void) noexcept'

Error compiling Cython file:
------------------------------------------------------------
...

Py_AtExit(_cleanup)


nfft_flags_dict = {
    'PRE_PHI_HUT':PRE_PHI_HUT,
                  ^
------------------------------------------------------------

pynfft/nfft.pyx:45:18: undeclared name not builtin: PRE_PHI_HUT

Error compiling Cython file:
------------------------------------------------------------
...
Py_AtExit(_cleanup)


nfft_flags_dict = {
    'PRE_PHI_HUT':PRE_PHI_HUT,
    'FG_PSI':FG_PSI,
             ^
------------------------------------------------------------

pynfft/nfft.pyx:46:13: undeclared name not builtin: FG_PSI

Error compiling Cython file:
------------------------------------------------------------
...


nfft_flags_dict = {
    'PRE_PHI_HUT':PRE_PHI_HUT,
    'FG_PSI':FG_PSI,
    'PRE_LIN_PSI':PRE_LIN_PSI,
                  ^
------------------------------------------------------------

pynfft/nfft.pyx:47:18: undeclared name not builtin: PRE_LIN_PSI

Error compiling Cython file:
------------------------------------------------------------
...

nfft_flags_dict = {
    'PRE_PHI_HUT':PRE_PHI_HUT,
    'FG_PSI':FG_PSI,
    'PRE_LIN_PSI':PRE_LIN_PSI,
    'PRE_FG_PSI':PRE_FG_PSI,
                 ^
------------------------------------------------------------

pynfft/nfft.pyx:48:17: undeclared name not builtin: PRE_FG_PSI

Error compiling Cython file:
------------------------------------------------------------
...
nfft_flags_dict = {
    'PRE_PHI_HUT':PRE_PHI_HUT,
    'FG_PSI':FG_PSI,
    'PRE_LIN_PSI':PRE_LIN_PSI,
    'PRE_FG_PSI':PRE_FG_PSI,
    'PRE_PSI':PRE_PSI,
              ^
------------------------------------------------------------

pynfft/nfft.pyx:49:14: undeclared name not builtin: PRE_PSI

Error compiling Cython file:
------------------------------------------------------------
...
    'PRE_PHI_HUT':PRE_PHI_HUT,
    'FG_PSI':FG_PSI,
    'PRE_LIN_PSI':PRE_LIN_PSI,
    'PRE_FG_PSI':PRE_FG_PSI,
    'PRE_PSI':PRE_PSI,
    'PRE_FULL_PSI':PRE_FULL_PSI,
                   ^
------------------------------------------------------------

pynfft/nfft.pyx:50:19: undeclared name not builtin: PRE_FULL_PSI

Error compiling Cython file:
------------------------------------------------------------
...
    'FG_PSI':FG_PSI,
    'PRE_LIN_PSI':PRE_LIN_PSI,
    'PRE_FG_PSI':PRE_FG_PSI,
    'PRE_PSI':PRE_PSI,
    'PRE_FULL_PSI':PRE_FULL_PSI,
    'MALLOC_X':MALLOC_X,
               ^
------------------------------------------------------------

pynfft/nfft.pyx:51:15: undeclared name not builtin: MALLOC_X

Error compiling Cython file:
------------------------------------------------------------
...
    'PRE_LIN_PSI':PRE_LIN_PSI,
    'PRE_FG_PSI':PRE_FG_PSI,
    'PRE_PSI':PRE_PSI,
    'PRE_FULL_PSI':PRE_FULL_PSI,
    'MALLOC_X':MALLOC_X,
    'MALLOC_F_HAT':MALLOC_F_HAT,
                   ^
------------------------------------------------------------

pynfft/nfft.pyx:52:19: undeclared name not builtin: MALLOC_F_HAT

Error compiling Cython file:
------------------------------------------------------------
...
    'PRE_FG_PSI':PRE_FG_PSI,
    'PRE_PSI':PRE_PSI,
    'PRE_FULL_PSI':PRE_FULL_PSI,
    'MALLOC_X':MALLOC_X,
    'MALLOC_F_HAT':MALLOC_F_HAT,
    'MALLOC_F':MALLOC_F,
               ^
------------------------------------------------------------

pynfft/nfft.pyx:53:15: undeclared name not builtin: MALLOC_F

Error compiling Cython file:
------------------------------------------------------------
...
    'PRE_PSI':PRE_PSI,
    'PRE_FULL_PSI':PRE_FULL_PSI,
    'MALLOC_X':MALLOC_X,
    'MALLOC_F_HAT':MALLOC_F_HAT,
    'MALLOC_F':MALLOC_F,
    'FFT_OUT_OF_PLACE':FFT_OUT_OF_PLACE,
                       ^
------------------------------------------------------------

pynfft/nfft.pyx:54:23: undeclared name not builtin: FFT_OUT_OF_PLACE

Error compiling Cython file:
------------------------------------------------------------
...
    'PRE_FULL_PSI':PRE_FULL_PSI,
    'MALLOC_X':MALLOC_X,
    'MALLOC_F_HAT':MALLOC_F_HAT,
    'MALLOC_F':MALLOC_F,
    'FFT_OUT_OF_PLACE':FFT_OUT_OF_PLACE,
    'FFTW_INIT':FFTW_INIT,
                ^
------------------------------------------------------------

pynfft/nfft.pyx:55:16: undeclared name not builtin: FFTW_INIT

Error compiling Cython file:
------------------------------------------------------------
...
    'MALLOC_X':MALLOC_X,
    'MALLOC_F_HAT':MALLOC_F_HAT,
    'MALLOC_F':MALLOC_F,
    'FFT_OUT_OF_PLACE':FFT_OUT_OF_PLACE,
    'FFTW_INIT':FFTW_INIT,
    'NFFT_SORT_NODES':NFFT_SORT_NODES,
                      ^
------------------------------------------------------------

pynfft/nfft.pyx:56:22: undeclared name not builtin: NFFT_SORT_NODES

Error compiling Cython file:
------------------------------------------------------------
...
    'MALLOC_F_HAT':MALLOC_F_HAT,
    'MALLOC_F':MALLOC_F,
    'FFT_OUT_OF_PLACE':FFT_OUT_OF_PLACE,
    'FFTW_INIT':FFTW_INIT,
    'NFFT_SORT_NODES':NFFT_SORT_NODES,
    'NFFT_OMP_BLOCKWISE_ADJOINT':NFFT_OMP_BLOCKWISE_ADJOINT,
                                 ^
------------------------------------------------------------

pynfft/nfft.pyx:57:33: undeclared name not builtin: NFFT_OMP_BLOCKWISE_ADJOINT

Error compiling Cython file:
------------------------------------------------------------
...
    'MALLOC_F':MALLOC_F,
    'FFT_OUT_OF_PLACE':FFT_OUT_OF_PLACE,
    'FFTW_INIT':FFTW_INIT,
    'NFFT_SORT_NODES':NFFT_SORT_NODES,
    'NFFT_OMP_BLOCKWISE_ADJOINT':NFFT_OMP_BLOCKWISE_ADJOINT,
    'PRE_ONE_PSI':PRE_ONE_PSI,
                  ^
------------------------------------------------------------

pynfft/nfft.pyx:58:18: undeclared name not builtin: PRE_ONE_PSI

Error compiling Cython file:
------------------------------------------------------------
...
    }

nfft_flags = copy.copy(nfft_flags_dict)

fftw_flags_dict = {
    'FFTW_ESTIMATE':FFTW_ESTIMATE,
                    ^
------------------------------------------------------------

pynfft/nfft.pyx:64:20: undeclared name not builtin: FFTW_ESTIMATE

Error compiling Cython file:
------------------------------------------------------------
...

nfft_flags = copy.copy(nfft_flags_dict)

fftw_flags_dict = {
    'FFTW_ESTIMATE':FFTW_ESTIMATE,
    'FFTW_DESTROY_INPUT':FFTW_DESTROY_INPUT,
                         ^
------------------------------------------------------------

pynfft/nfft.pyx:65:25: undeclared name not builtin: FFTW_DESTROY_INPUT

Error compiling Cython file:
------------------------------------------------------------
...
# initialize FFTW threads
fftw_init_threads()

# register cleanup callbacks
cdef void _cleanup():
    fftw_cleanup()
    ^
------------------------------------------------------------

pynfft/nfft.pyx:38:4: undeclared name not builtin: fftw_cleanup

Error compiling Cython file:
------------------------------------------------------------
...
fftw_init_threads()

# register cleanup callbacks
cdef void _cleanup():
    fftw_cleanup()
    fftw_cleanup_threads()
    ^
------------------------------------------------------------

pynfft/nfft.pyx:39:4: undeclared name not builtin: fftw_cleanup_threads

Error compiling Cython file:
------------------------------------------------------------
...
        if p_n == NULL:
            raise MemoryError
        for t in range(d):
            p_n[t] = n[t]

        nfft_init_guru(&self._plan, d, p_N, M, p_n, m,
        ^
------------------------------------------------------------

pynfft/nfft.pyx:225:8: undeclared name not builtin: nfft_init_guru

Error compiling Cython file:
------------------------------------------------------------
...
        if p_n == NULL:
            raise MemoryError
        for t in range(d):
            p_n[t] = n[t]

        nfft_init_guru(&self._plan, d, p_N, M, p_n, m,
                                       ^
------------------------------------------------------------

pynfft/nfft.pyx:225:39: Cannot convert 'int *' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        if p_n == NULL:
            raise MemoryError
        for t in range(d):
            p_n[t] = n[t]

        nfft_init_guru(&self._plan, d, p_N, M, p_n, m,
                                               ^
------------------------------------------------------------

pynfft/nfft.pyx:225:47: Cannot convert 'int *' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        Default value is ``flags = ('PRE_PHI_HUT', 'PRE_PSI')``.
        '''
        pass

    def __dealloc__(self):
        nfft_finalize(&self._plan)
        ^
------------------------------------------------------------

pynfft/nfft.pyx:306:8: undeclared name not builtin: nfft_finalize

Error compiling Cython file:
------------------------------------------------------------
...
            self._adjoint()
        return self.f_hat

    cdef void _precompute(self):
        with nogil:
            nfft_precompute_one_psi(&self._plan)
            ^
------------------------------------------------------------

pynfft/nfft.pyx:344:12: undeclared name not builtin: nfft_precompute_one_psi

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_precompute_one_psi(&self._plan)

    cdef void _trafo(self):
        with nogil:
            nfft_trafo(&self._plan)
            ^
------------------------------------------------------------

pynfft/nfft.pyx:348:12: undeclared name not builtin: nfft_trafo

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_trafo(&self._plan)

    cdef void _trafo_direct(self):
        with nogil:
            nfft_trafo_direct(&self._plan)
            ^
------------------------------------------------------------

pynfft/nfft.pyx:352:12: undeclared name not builtin: nfft_trafo_direct

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_trafo_direct(&self._plan)

    cdef void _adjoint(self):
        with nogil:
            nfft_adjoint(&self._plan)
            ^
------------------------------------------------------------

pynfft/nfft.pyx:356:12: undeclared name not builtin: nfft_adjoint

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_adjoint(&self._plan)

    cdef void _adjoint_direct(self):
        with nogil:
            nfft_adjoint_direct(&self._plan)
            ^
------------------------------------------------------------

pynfft/nfft.pyx:360:12: undeclared name not builtin: nfft_adjoint_direct

Error compiling Cython file:
------------------------------------------------------------
...
            self._adjoint()
        return self.f_hat

    cdef void _precompute(self):
        with nogil:
            nfft_precompute_one_psi(&self._plan)
                                   ^
------------------------------------------------------------

pynfft/nfft.pyx:344:35: Discarding owned Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
            self._adjoint()
        return self.f_hat

    cdef void _precompute(self):
        with nogil:
            nfft_precompute_one_psi(&self._plan)
                                   ^
------------------------------------------------------------

pynfft/nfft.pyx:344:35: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
            self._adjoint()
        return self.f_hat

    cdef void _precompute(self):
        with nogil:
            nfft_precompute_one_psi(&self._plan)
            ^
------------------------------------------------------------

pynfft/nfft.pyx:344:12: Accessing Python global or builtin not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
            self._adjoint()
        return self.f_hat

    cdef void _precompute(self):
        with nogil:
            nfft_precompute_one_psi(&self._plan)
                                   ^
------------------------------------------------------------

pynfft/nfft.pyx:344:35: Constructing Python tuple not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
            self._adjoint()
        return self.f_hat

    cdef void _precompute(self):
        with nogil:
            nfft_precompute_one_psi(&self._plan)
                                    ^
------------------------------------------------------------

pynfft/nfft.pyx:344:36: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_precompute_one_psi(&self._plan)

    cdef void _trafo(self):
        with nogil:
            nfft_trafo(&self._plan)
                      ^
------------------------------------------------------------

pynfft/nfft.pyx:348:22: Discarding owned Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_precompute_one_psi(&self._plan)

    cdef void _trafo(self):
        with nogil:
            nfft_trafo(&self._plan)
                      ^
------------------------------------------------------------

pynfft/nfft.pyx:348:22: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_precompute_one_psi(&self._plan)

    cdef void _trafo(self):
        with nogil:
            nfft_trafo(&self._plan)
            ^
------------------------------------------------------------

pynfft/nfft.pyx:348:12: Accessing Python global or builtin not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_precompute_one_psi(&self._plan)

    cdef void _trafo(self):
        with nogil:
            nfft_trafo(&self._plan)
                      ^
------------------------------------------------------------

pynfft/nfft.pyx:348:22: Constructing Python tuple not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_precompute_one_psi(&self._plan)

    cdef void _trafo(self):
        with nogil:
            nfft_trafo(&self._plan)
                       ^
------------------------------------------------------------

pynfft/nfft.pyx:348:23: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_trafo(&self._plan)

    cdef void _trafo_direct(self):
        with nogil:
            nfft_trafo_direct(&self._plan)
                             ^
------------------------------------------------------------

pynfft/nfft.pyx:352:29: Discarding owned Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_trafo(&self._plan)

    cdef void _trafo_direct(self):
        with nogil:
            nfft_trafo_direct(&self._plan)
                             ^
------------------------------------------------------------

pynfft/nfft.pyx:352:29: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_trafo(&self._plan)

    cdef void _trafo_direct(self):
        with nogil:
            nfft_trafo_direct(&self._plan)
            ^
------------------------------------------------------------

pynfft/nfft.pyx:352:12: Accessing Python global or builtin not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_trafo(&self._plan)

    cdef void _trafo_direct(self):
        with nogil:
            nfft_trafo_direct(&self._plan)
                             ^
------------------------------------------------------------

pynfft/nfft.pyx:352:29: Constructing Python tuple not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_trafo(&self._plan)

    cdef void _trafo_direct(self):
        with nogil:
            nfft_trafo_direct(&self._plan)
                              ^
------------------------------------------------------------

pynfft/nfft.pyx:352:30: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_trafo_direct(&self._plan)

    cdef void _adjoint(self):
        with nogil:
            nfft_adjoint(&self._plan)
                        ^
------------------------------------------------------------

pynfft/nfft.pyx:356:24: Discarding owned Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_trafo_direct(&self._plan)

    cdef void _adjoint(self):
        with nogil:
            nfft_adjoint(&self._plan)
                        ^
------------------------------------------------------------

pynfft/nfft.pyx:356:24: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_trafo_direct(&self._plan)

    cdef void _adjoint(self):
        with nogil:
            nfft_adjoint(&self._plan)
            ^
------------------------------------------------------------

pynfft/nfft.pyx:356:12: Accessing Python global or builtin not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_trafo_direct(&self._plan)

    cdef void _adjoint(self):
        with nogil:
            nfft_adjoint(&self._plan)
                        ^
------------------------------------------------------------

pynfft/nfft.pyx:356:24: Constructing Python tuple not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_trafo_direct(&self._plan)

    cdef void _adjoint(self):
        with nogil:
            nfft_adjoint(&self._plan)
                         ^
------------------------------------------------------------

pynfft/nfft.pyx:356:25: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_adjoint(&self._plan)

    cdef void _adjoint_direct(self):
        with nogil:
            nfft_adjoint_direct(&self._plan)
                               ^
------------------------------------------------------------

pynfft/nfft.pyx:360:31: Discarding owned Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_adjoint(&self._plan)

    cdef void _adjoint_direct(self):
        with nogil:
            nfft_adjoint_direct(&self._plan)
                               ^
------------------------------------------------------------

pynfft/nfft.pyx:360:31: Calling gil-requiring function not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_adjoint(&self._plan)

    cdef void _adjoint_direct(self):
        with nogil:
            nfft_adjoint_direct(&self._plan)
            ^
------------------------------------------------------------

pynfft/nfft.pyx:360:12: Accessing Python global or builtin not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_adjoint(&self._plan)

    cdef void _adjoint_direct(self):
        with nogil:
            nfft_adjoint_direct(&self._plan)
                               ^
------------------------------------------------------------

pynfft/nfft.pyx:360:31: Constructing Python tuple not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...
        with nogil:
            nfft_adjoint(&self._plan)

    cdef void _adjoint_direct(self):
        with nogil:
            nfft_adjoint_direct(&self._plan)
                                ^
------------------------------------------------------------

pynfft/nfft.pyx:360:32: Converting to Python object not allowed without gil
Traceback (most recent call last):
  File "/home/pc266769/gits/nsp/code/pyNFFT/setup.py", line 314, in <module>
    setup_package()
  File "/home/pc266769/gits/nsp/code/pyNFFT/setup.py", line 304, in setup_package
    extensions = get_cython_extensions()
  File "/home/pc266769/gits/nsp/code/pyNFFT/setup.py", line 89, in get_cython_extensions
    return cythonize(ext_modules)
  File "/volatile/pierre-antoine/.pyenv/versions/fmri/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
    cythonize_one(*args)
  File "/volatile/pierre-antoine/.pyenv/versions/fmri/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /home/pc266769/gits/nsp/code/pyNFFT/pynfft/nfft.pyx
```

[^1]:https://cython.readthedocs.io/en/latest/src/changes.html#unified-release-notes

**Comment by paquiteau** [comment]
#76 Fixes it. Thank you @chaithyagr
